### ISSUE TITLE
refreshing the page causes user to have to login again

### ISSUE THREAD

**Issue by timjoyce11** [auth0-samples/auth0-vue-samples#101]
in chrome, if I hit Refresh, then the user is required to re-login.   how do I overcome this?

**Comment by adamjmcgrath** [comment]
Hi @timjoyce11 

Are you using a Social Connection (like Google) to login? If this is the case you will have to configure it with your own Developer Keys in order for `getTokenSilently` to work correctly and the app to silently log the use in on page refresh.

See: https://auth0.com/docs/connections/social/devkeys#limitations-of-developer-keys

**Comment by timjoyce11** [comment]
Adam,

thank you so much for pointing me in the right direction and understanding my issue from such scant information.  it all works now.  thanks to you.

stay well

tim
