### ISSUE TITLE
Login the successful login

### ISSUE THREAD

**Issue by daveKoala** [auth0-samples/auth0-vue-samples#102]
Hi Steve Hobbs,
Great wee package. One question the project i am working on has a logging service that catches API calls and a bunch of other things.

I am trying to capture the point where a user successfully logs in within the authWrapper.js -> useAuth0 method. Currently the previous dev team added it to the .finally of the 'created' method after dispatching an action to take the Auth0 token and querying another service. But this is triggered by page refreshes.

Any thoughts?

Cheers

**Comment by stevehobbsdev** [comment]
Unfortunately we don't have a good event model for reporting this kind of information, either from the SDK or the Vue wrapper. It will be triggered by page refreshes as the SDK has to effectively log in again when the page is initialized.

The only thing I can recommend is reconfiguring the wrapper to capture that information once [when Auth0 calls back to your app](https://github.com/auth0-samples/auth0-vue-samples/blob/master/01-Login/src/auth/authWrapper.js#L51) and cache that info somewhere. The cache could then be invalidated on logout.

Closing for now but feel free to continue the discussion if you need further assistance.
