### ISSUE TITLE
handleRedirectCallback usage

### ISSUE THREAD

**Issue by smakinson** [auth0-samples/auth0-vue-samples#104]
https://github.com/auth0-samples/auth0-vue-samples/blob/c0b9cedec9b4b41c334de4b9052952985fce0384/01-Login/src/auth/authWrapper.js#L45

Is the above function used anywhere?

**Comment by stevehobbsdev** [comment]
Not by the sample, but could potentially be used by the app developer. The idea behind that wrapper is that it could in the future be extracted into a library in its own right, so we included the full API here.

Closing for now but feel free to continue the conversation.

**Comment by changetocoding** [comment]
Just around that function. Is authenticated is always set to true in it. Is that correct? 

```js
this.isAuthenticated = true;
```

In loginWithPopup() the behaviour is different:

```js
this.isAuthenticated = await this.auth0Client.isAuthenticated();
```

Also would argue for removing it or at least renaming it, as it causes confusion with this method:
```
this.auth0Client.handleRedirectCallback()
```
