### ISSUE TITLE
Question: Why declare a new Vue instance in the plugin?

### ISSUE THREAD

**Issue by godd9170** [auth0-samples/auth0-vue-samples#105]
Apologies if this isn't the right place to ask this, please close and redirect me if there's a better spot.

I'm curious why both the examples in this repo elect to construct an entirely new `Vue` instance in the plugin like this. 

https://github.com/auth0-samples/auth0-vue-samples/blob/c0b9cedec9b4b41c334de4b9052952985fce0384/01-Login/src/auth/authWrapper.js#L18

Why this pattern versus simply defining global methods, like suggested inthe Vue documentation [here](https://vuejs.org/v2/guide/plugins.html)?

**Comment by stevehobbsdev** [comment]
Thanks for raising. We mainly do that for the reactivity you get out of the box for properties like `isLoading`, `isAuthenticated`, `user`, etc. When the auth state changes it enables us to propagate those changes easily.

**Comment by godd9170** [comment]
Thanks for the quick reply @stevehobbsdev. That definitely makes sense. I'm curious though, as I'm still pretty new to Vue, if it's kosher to construct a new instance in a plugin. Is this something you'd recommend in a non-example, production setting?

**Comment by stevehobbsdev** [comment]
Sure, this should be no problem. All the components you create in your app are just [Vue instances with a name](https://vuejs.org/v2/guide/components.html); think of auth wrapper in this sample as just another component that does not have a render template.

Here's a [quick thread](https://forum.vuejs.org/t/multiple-vue-js-instances-vs-performance/20399) I found on performance, which might alleviate concerns.
