### ISSUE TITLE
Support useRefreshTokens in auth0client

### ISSUE THREAD

**Issue by glorat** [auth0-samples/auth0-vue-samples#106]
Any reason why we shouldn't use `useRefreshTokens` to make use of rotating refresh tokens if enabled ? If not, seems like a good optional addition to the plug-in.

**Comment by stevehobbsdev** [comment]
Thanks for the feedback. There's no reason, it's just the plugin sample code hasn't be updated to handle this scenario yet. I'm planning on a quick sweep through the samples in the short term, I'll take this into account. 

Thanks!
