### ISSUE TITLE
Why i lost  user data e.g name picture .. etc when i refresh page ?

### ISSUE THREAD

**Issue by AREEG94FAHAD** [auth0-samples/auth0-vue-samples#107]

**Comment by stevehobbsdev** [comment]
@AREEG94FAHAD This could be down to a few things:

* You are using a browser such as Safari or Brave where third-party cookies are blocked by default. If so, please test your app using Chrome to see if the application works as expected then
* You do not have your *Allowed Web Origins* configured in your [Auth0 dashboard](https://manage.auth0.com). There should be an entry there for your application origin
* Check you are not getting any errors in your browser console window
