### ISSUE TITLE
What is the API IDENTIFIER in Scenario #2 - Calling an External API

### ISSUE THREAD

**Issue by jsappme** [auth0-samples/auth0-vue-samples#115]
Could you please tell me what should I enter for this following variable?

```"audience": "<YOUR AUTH0 API IDENTIFIER>",```

**Comment by stevehobbsdev** [comment]
Hi, apologies for the radio silence here.

In case you haven't got this working yet, you should set this value to the API identifier of the API you wish to get an access token for to call APIs.

![image](https://user-images.githubusercontent.com/766403/92100718-0d49a000-edd4-11ea-9340-14252c0879db.png)

If you don't need to call an API, you can leave out the `audience` setting altogether.

Hope that helps!
