### ISSUE TITLE
Vue.js Example '01-login' fails with 401 unauthorized

### ISSUE THREAD

**Issue by xetra11** [auth0-samples/auth0-vue-samples#118]
I downloaded the example and ran it as described in the quickstart guide.
The app starts fine and also the Auth0 Login works with my Google Account.

However after I log in (or better said sign up since this is the first attempt with my Google Account). The page returns the following:

![image](https://user-images.githubusercontent.com/8149023/91165777-90327280-e6d1-11ea-9aea-73f2b1110e5c.png)

The chrome dev tools panel shows me a 401 error code from that request `https://alemanni-game.eu.auth0.com/oauth/token` and the response is:
```
{"error":"access_denied","error_description":"Unauthorized"}
```
The logs show me the following:

![image](https://user-images.githubusercontent.com/8149023/91165969-e8697480-e6d1-11ea-89c1-0619191058ce.png)

Here the details of the 'Failed Exchange':

```
{
  "date": "2020-08-25T10:48:24.338Z",
  "type": "feacft",
  "description": "Unauthorized",
  "connection_id": "",
  "client_id": "<client_id>",
  "client_name": null,
  "ip": "78.35.206.11",
  "user_agent": "Chrome 83.0.4103 / Linux 0.0.0",
  "details": {
    "code": "*************b8p"
  },
  "hostname": "alemanni-game.eu.auth0.com",
  "user_id": "",
  "user_name": "",
  "log_id": "90020200825104825180000599953486520206291538153981345826",
  "_id": "90020200825104825180000599953486520206291538153981345826",
  "isMobile": false
}
```
I am using a Single Page Application:
![image](https://user-images.githubusercontent.com/8149023/91166162-34b4b480-e6d2-11ea-8a6a-501e02e985a3.png)

And the API is the default 'Auth0 Management API'. Somebody said I need to configure Machine to Machine Applications in that API - however the search input field in there does not yield any results to I can not configure anything.

I am very confused why that example does not work in my case :(

PS: Every whitelisting in the Application settings was set to `http://localhost:3000`

**Comment by AntMarras** [comment]
is this the issue?

https://community.auth0.com/t/401-unauthorized-when-obtaining-token-in-authorization-code-grant/44685
