### ISSUE TITLE
How to go from client to server API

### ISSUE THREAD

**Issue by bahmutov** [auth0-samples/auth0-vue-samples#12]
The client SPA logs in and gets access token and id token. When making authorized requests,
we pass id_token in the header (via HTTP interceptor).

How would a server verify the user identify in this case? Should it be access token instead? Is this an example of "implicit grant"?

Any advice would be appreciated.

**Comment by chenkie** [comment]
Hi @bahmutov, have a look at the [latest OIDC sample](https://github.com/auth0-samples/auth0-vue-samples/tree/OIDC/05-Authorization) for a complete setup including a Node server :) It uses the implicit grant and sends the `access_token` to the server.

**Comment by bahmutov** [comment]
thank you, will use that
