### ISSUE TITLE
Logout redirect does not work

### ISSUE THREAD

**Issue by SergioEanX** [auth0-samples/auth0-vue-samples#122]
Logout route redirect me to http://localhost without port. 
How to fix it?

**Comment by stevehobbsdev** [comment]
Hey @SergioEanX , you will need to call logout and pass a `returnTo` option, like so:

```
$auth.logout({ returnTo: 'http://localhost:3000' });
```

This URL also needs to appear in the **Allowed Logout URLs** setting for your Auth0 app. (see [Redirect users after logout](https://auth0.com/docs/logout/redirect-users-after-logout))

Hope that helps!
