### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by aberenyi** [auth0-samples/auth0-vue-samples#123]
Hi,

Any chance for a Vue 3.x version?

I find [this](https://blog.risingstack.com/auth0-vue-typescript-quickstart-docs/) howto pretty comprehensive, however, there are some gotchas, e.g. plugin installation has changed completely ([globalProperties](https://v3.vuejs.org/api/application-config.html#globalproperties) or [provide/inject](https://v3.vuejs.org/api/application-api.html#provide) can be used).

IMHO it would be super useful.

Cheers

**Comment by stevehobbsdev** [comment]
Thanks for raising this @aberenyi. We don't have any immediate plans to upgrade the sample just yet, but it's certainly on the the roadmap for the future.

**Comment by john-craft** [comment]
> Thanks for raising this **aberenyi**. We don't have any immediate plans to upgrade the sample just yet, but it's certainly on the the roadmap for the future

Would very much appreciate a Vue 3 version of this sample project.
