### ISSUE TITLE
Does not work with Vue 3

### ISSUE THREAD

**Issue by InspectorJapp** [auth0-samples/auth0-vue-samples#127]
The samples need to be updated for Vue 3

**Comment by evansims** [comment]
Hey @InspectorJapp 👋 Thanks for raising this! We don't currently have any immediate plans to upgrade this sample, but it's on our roadmap for later! (See also: #123)

**Comment by InspectorJapp** [comment]
Ok, I only just now noticed that @aberenyi previously opened an issue for the same problem.

Why not just keep the issue open so that others know that you guys have it on the roadmap?
