### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by radiantone** [auth0-samples/auth0-vue-samples#129]
Using chrome, there are multiple console errors regarding loading https over http. The app cannot load https over http and since it does not run with https, it is broken.

Running the app using localhost produces

Failed to load resource: the server responded with a status of 403 ()

when loading from my auth0 app.

On top of that, the main page has no login button or link, so not sure how to demo logging in. And it also does not have a link to /profile (gated resource). Manually adding /profile to the url produces a blank page.

**Comment by stevehobbsdev** [comment]
Thanks for raising @radiantone. Sounds like there's an issue getting the callback from Auth0, which has an impact on showing the login buttons, and it could be down to configuration. A common cause of this is omitting the "Allowed Web Origins" setting from your Auth0 app settings.

Also, could you check your [Auth0 Logs](https://auth0.com/#/logs) to see if that presents any more insight into the problem you're seeing?

**Comment by radiantone** [comment]
Ahhhh. I see this 
Callback URL mismatch. http://localhost:3000 is not in the list of allowed callback URLs

Probably something that should be mentioned in the README, how to avoid this.

**Comment by stevehobbsdev** [comment]
Thanks @radiantone. These samples are a companion to the quickstart guides that are available on the Auth0 docs site - https://auth0.com/docs/quickstart/spa/vuejs

The first part of this should get you moving with the Auth0 setup. Sounds like there's an opportunity for us to replicate some of that directly on the readme here - not just for this sample, but some of the others too.

**Comment by radiantone** [comment]
Followed the directions on the quickstart. Still doesn't work. Browser throws this error.

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in created hook (Promise/async): "Error: 
      auth0-spa-js must run on a secure origin. See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.
    "

(found in <Root>)
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
eval @ vue.runtime.esm.js?2b0e:1856
Promise.catch (async)
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1856
callHook @ vue.runtime.esm.js?2b0e:4219
Vue._init @ vue.runtime.esm.js?2b0e:5008
Vue @ vue.runtime.esm.js?2b0e:5085
useAuth0 @ authWrapper.js?de49:18
install @ authWrapper.js?de49:105
Vue.use @ vue.runtime.esm.js?2b0e:5107
eval @ main.js?56d7:17
./src/main.js @ app.js:1388
__webpack_require__ @ app.js:849
fn @ app.js:151
1 @ app.js:1485
__webpack_require__ @ app.js:849
checkDeferredModules @ app.js:46
(anonymous) @ app.js:925
(anonymous) @ app.js:928
vue.runtime.esm.js?2b0e:1888 Error: 
      auth0-spa-js must run on a secure origin. See https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin for more information.
    
    at eval (auth0-spa-js.production.esm.js?9767:15)
    at new e (auth0-spa-js.production.esm.js?9767:15)
    at eval (auth0-spa-js.production.esm.js?9767:15)
    at eval (auth0-spa-js.production.esm.js?9767:15)
    at Object.eval [as next] (auth0-spa-js.production.esm.js?9767:15)
    at eval (auth0-spa-js.production.esm.js?9767:15)
    at new Promise (<anonymous>)
    at r (auth0-spa-js.production.esm.js?9767:15)
    at Vo (auth0-spa-js.production.esm.js?9767:15)
    at Vue._callee3$ (authWrapper.js?de49:18)
logError @ vue.runtime.esm.js?2b0e:1888
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
eval @ vue.runtime.esm.js?2b0e:1856
Promise.catch (async)
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1856
callHook @ vue.runtime.esm.js?2b0e:4219
Vue._init @ vue.runtime.esm.js?2b0e:5008
Vue @ vue.runtime.esm.js?2b0e:5085
useAuth0 @ authWrapper.js?de49:18
install @ authWrapper.js?de49:105
Vue.use @ vue.runtime.esm.js?2b0e:5107
eval @ main.js?56d7:17
./src/main.js @ app.js:1388
__webpack_require__ @ app.js:849
fn @ app.js:151
1 @ app.js:1485
__webpack_require__ @ app.js:849
checkDeferredModules @ app.js:46
(anonymous) @ app.js:925
(anonymous) @ app.js:928
```

App page has no login button or anything. Just shows some information. So not sure what I should be seeing.
![auth0-error](https://user-images.githubusercontent.com/25509097/102375842-f6991480-3f90-11eb-8937-1e180a34339b.png)

**Comment by frederikprijck** [comment]
It looks like you are running your application without https on a domain that is different from localhost.

The error message includes a link to https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-auth0-spa-js-must-run-on-a-secure-origin which explains the problem.
