### ISSUE TITLE
Files not in sync with the docs

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [auth0-samples/auth0-vue-samples#131]
I see that some files in the samples doesn't accurately reflect the code in the docs. For eg. https://github.com/auth0-samples/auth0-vue-samples/blob/master/01-Login/src/auth/authWrapper.js is not exactly what is shown in https://auth0.com/docs/quickstart/spa/vuejs/01-login#create-an-authentication-wrapper. Is this intended and if so which one of these snippets are more updated?

**Comment by frederikprijck** [comment]
The difference between the two is that the sample is correctly handling `loginWithPopup`:

```
async loginWithPopup(options, config) {
        this.popupOpen = true;

        try {
          await this.auth0Client.loginWithPopup(options, config);
          this.user = await this.auth0Client.getUser();
          this.isAuthenticated = await this.auth0Client.isAuthenticated();
          this.error = null;
        } catch (e) {
          console.error(e);
          this.error = e;
        } finally {
          this.popupOpen = false;
        }
      },
```

I opened a PR to update the Quickstart https://github.com/auth0/docs/pull/9550/files
