### ISSUE TITLE
Vue SPA + API backend

### ISSUE THREAD

**Issue by alsyia** [auth0-samples/auth0-vue-samples#132]
Hello,

I'm trying to make the Vue sample work in my application. I copy/pasted the sample plugin code and installed it properly into my Vue app. Now, I would like my app to automatically initiate the login flow when somebody open the app without being logged in.

The first thing I did was something like this:

   ```vue
<script>
export default {
  watch: { // Use a watcher because Auth0Client is instantiated asynchronously
    authLoaded: function(newValue) {
      if (newValue) {
        this.$auth.loginWithRedirect();
      }
    }
  },
  computed: {
    authLoaded() {
      return !this.$auth.loading;
    }
  }
};
</script>

<template>
  <div id="app" v-if="!$auth.isLoading && $auth.isAuthenticated">
    // App content
  </div>
</template>

<style></style>
```

This triggers the login process correctly, but it obviously does it everytime, including if the user just logged in. So I did this:

```vue
<script>
export default {
  watch: {
    authLoaded: function(newValue) {
      if (newValue) {
        this.$auth
          .getTokenSilently()
          .then(token => console.log(token) // For debugging purposes only)
          .catch(error => {
            this.$auth.loginWithRedirect();
          });
      }
    }
  },
  computed: {
    authLoaded() {
      return !this.$auth.loading;
    }
  }
};
</script>

<template>
  <div id="app" v-if="!$auth.isLoading && $auth.isAuthenticated">
  // App content
  </div>
</template>

<style></style>
```

It doesn't really work, because I'm redirected correctly to my App, the token is fetched and it works, but if I refresh the page, I have to login entirely again. Why is that? I thought getTokenSilently would use my auth0 cookie, or something like that?
I also have a few weird things:
* I still get a `Login required` error logged in the Console. I thought catching on the Promise should have got rid of that, but I might be wrong? It looks like this:
![image](https://user-images.githubusercontent.com/4249034/105520696-50e96b80-5cdb-11eb-8d31-0895a0caf915.png)
* I also get a `GET https://mytenant.eu.auth0.com/user/ssodata 404` error in the console. This doesn't look related to my code, but did I miss a configuration somewhere in Auth0?
* Last but not least, I get a `Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/".` error. My understanding is that the plugin redirects to the current path if no `appState` has been provided, and since `appState` is the return value of the `handleRedirectCallback` method which doesn't return anything, it's always empty. Anyway, is this intended behaviour?

One last question: I don't use Vuex on my app for now, what would be the best way to store the token and make it available for, e.g., Axios in other components? I have a Flask backend I would like to contact with my newly obtained token. Am I on the right track here?

Sorry for the long post, and thank you for your help!

**Comment by stevehobbsdev** [comment]
👋 Thanks for your patience here. Let me respond to each thing in the post.

> I thought getTokenSilently would use my auth0 cookie, or something like that?

There are some nuances to this and it depends on what browser you're testing this in. If you're using a browser that blocks third-party cookies by default (e.g. Safari, Brave) then Auth0 can't actually read your Auth0 cookie when calling `getTokenSilently`, and so you get the `login_required` error you're seeing in the console. However, this should currently work in Chrome. We have an [awesome post on our Community site](https://community.auth0.com/t/why-is-authentication-lost-after-refreshing-my-single-page-application/56276/2) that explains this in more detail.

Looking at your code sample though, you probably just want to keep the check for `$auth.isAuthenticated` but not necessarily the check for the token, unless you actually want to use the token at that time. Something like this:

```js
<script>
export default {
  watch: {
    authLoaded: function(newValue) {
      if (newValue && !this.$auth.isAuthenticated) {
        this.$auth.loginWithRedirect();
      }
    }
  },
  computed: {
    authLoaded() {
      return !this.$auth.loading;
    }
  }
};
</script>

<template>
  <div id="app" v-if="!$auth.isLoading && $auth.isAuthenticated">
  // App content
  </div>
</template>

<style></style>
```

> I also get a GET https://mytenant.eu.auth0.com/user/ssodata 404 error in the console

I wouldn't worry about that too much as it won't affect your application; our Classic Login Experience sometimes throws this error but won't be giving you problems here.

> My understanding is that the plugin redirects to the current path if no appState has been provided, and since appState is the return value of the handleRedirectCallback method which doesn't return anything, it's always empty. Anyway, is this intended behaviour?

Yes - the [default handler](https://github.com/auth0-samples/auth0-vue-samples/blob/master/01-Login/src/auth/authWrapper.js#L5) ignores appState but you might want to override that handler if you are doing something special with appState. However, the [route guard](https://github.com/auth0-samples/auth0-vue-samples/blob/master/01-Login/src/auth/authGuard.js) makes use of it.

I haven't seen that error in normal running of the app though, are you doing something custom with the redirect callback? If not, perhaps the issues you're having with the login above may be causing this. Worth fixing those first then see if you still get the error.

Hope that helps!

**Comment by alsyia** [comment]
Thanks for the detailed answer!

The authentication lost at refresh issue was because I was using Auth0 dev keys for my SSO integration on this tenant, something I had totally overlooked. The post you linked is indeed awesome! It would deserve a place in the documentation imo.
The routing error disappeared too. :)

I modified the code to include your advice. It works very well, but I still have one concern: when refreshing the app, the `/authorize` request (which, I guess, is triggered by the checkSession call in the `createAuth0Client`) is somewhat slow:
![image](https://user-images.githubusercontent.com/4249034/106287755-7a5c4700-6247-11eb-8439-edbe4176abba.png)
Is this expected? Timings are consistent from one day to another, always around 2.5s.

This causes a noticeable lag for users since the app checks the autentication status before displaying most of the content. The only rules in this tenant are for the Authorization extension so no obvious cause of slowness here.

I'm using Chrome so I guess the Auth0 cookie is used for the silent login. Would refresh tokens be faster?

**Comment by stevehobbsdev** [comment]
Glad to hear it's working a bit better for you :)

> I'm using Chrome so I guess the Auth0 cookie is used for the silent login. Would refresh tokens stored in local storage be faster?

Yes - if you use [rotating refresh tokens](https://auth0.com/docs/tokens/refresh-tokens/refresh-token-rotation) in local storage, then your app is no longer reliant on the user's session (and thus the cookie) and just calls the token endpoint directly. You will get a slight performance benefit as well as being able to function in browsers where third-party cookies are blocked.

Otherwise, it uses an iframe and ultimately makes a couple of API calls (one of them to the authorization endpoint, which is primarily designed as an interactive flow) and as such can be a bit slower, hence the performance hit that you're seeing.

Hope that helps! I'll close this for now but very happy to continue the discussion if you have further questions.

**Comment by alsyia** [comment]
I think I have everything I need, thank you very much :)
