### ISSUE TITLE
Can you update the quick start guides with this code

### ISSUE THREAD

**Issue by changetocoding** [auth0-samples/auth0-vue-samples#133]
Hi can you update the quickstart guide and also the tutorial here: (https://auth0.com/blog/beginner-vuejs-tutorial-with-user-login/#) with this updated code. 

The code on the quickstart and on the tutorial feature a serious bug which was fixed in #91. Testing locally I was able to authenicate a user even though the loginWithPopup errored out. 

I'm guessing alot of people use the outdated code on the quickstart or that tutorial which contains the bug

Cheers,

**Comment by stevehobbsdev** [comment]
Thanks for reporting - let me update the quickstart with the latest code. I will also ping the team that looks after the blog to see if this can be amended.
