### ISSUE TITLE
isAuthenticated set to true in handleRedirectCallback

### ISSUE THREAD

**Issue by changetocoding** [auth0-samples/auth0-vue-samples#134]
https://github.com/auth0-samples/auth0-vue-samples/blob/43b71a0c21a46059a07e1f8ebbdd1fa2f239e738/01-Login/src/auth/authWrapper.js#L45

isAuthenticated is set to true, unless there is an error. Is that correct?

In loginWithPopup() the behaviour is different:
```
this.isAuthenticated = await this.auth0Client.isAuthenticated();
```

Also would argue for removing this function or at least renaming it, as it causes confusion with this method:

```
this.auth0Client.handleRedirectCallback()
```

**Comment by stevehobbsdev** [comment]
Thanks for reporting the discrepancy, I'll raise a PR to fix it.

> it causes confusion with this method:

Can you please elaborate on the confusion?

**Comment by changetocoding** [comment]
I was just confused between handleRedirectCallback(); and the auth0 version.  I think its fine to leave as is.

**Comment by stevehobbsdev** [comment]
It's a fair comment - one just wraps the other and sets some state. Ideally we wouldn't need this, and we'll do what our SDKs like [auth0-react](https://github.com/auth0/auth0-react) do and hide this from you completely.

**Comment by stevehobbsdev** [comment]
Closing for now as this will be handled when the samples are rewritten.
