### ISSUE TITLE
Login required after refreshing browser

### ISSUE THREAD

**Issue by r21nomi** [auth0-samples/auth0-vue-samples#136]
Hi, thank you for awesome samples.

I was trying `02-Calling-an-API` and login process got successful.
(I confirmed `$auth.isAuthenticated` is true and I checked user info.)

But `await createAuth0Client()` in `authWrapper.js` becomes error when I refresh browser.

I checked the log below on console.
<img src="https://user-images.githubusercontent.com/3589344/109747412-6a56cf00-7c1a-11eb-891e-bacd390346d8.png" width=400 />

Do you know the cause of this?

Thanks

**Comment by r21nomi** [comment]
I realized this would happen in only secret tab for chrome.
I confirmed `$auth.isAuthenticated` becomes true and the error `Login required` never happend on normal chrome tab.

**Comment by frederikprijck** [comment]
Hi, 

This is expected as explained in https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md (`Why is the user logged out when they refresh the page in their SPA?`).

An incognito tab in Chrome does not allow third party cookies so Silent Auth will not work unless you use Refresh Tokens.

Let me know if you need more guidance, but closing this for now.
