### ISSUE TITLE
I can't create a sample build in vue js v3 

### ISSUE THREAD

**Issue by furkanmeclis** [auth0-samples/auth0-vue-samples#143]
vue js v2 It does not support some libraries so I use v3 but I cannot use auth0 at this time.

**Comment by stevehobbsdev** [comment]
You are able to use Auth0, but unfortunately our samples have not been rewritten for Vue 3 yet. The samples here just wrap our [Auth0 SPA SDK](https://github.com/auth0/auth0-spa-js) library and the biggest problem is that they use the old Vue 2 Plugin API.

I don't have exact details to share yet but we aim to upgrade these samples to be compatible with Vue 3 soon.
