### ISSUE TITLE
Using getTokenSilently() doesn't update $auth.user object

### ISSUE THREAD

**Issue by ndenny** [auth0-samples/auth0-vue-samples#154]
Currently getTokenSilently() just wraps the internal client - but if you need to use this to get an updated token after, for example, adding new metadata to your user - the Vue object is not also refreshed to match with the updated data.

My suggested fix is:
```javascript
     async getTokenSilently(o) {
        const token = await this.auth0Client.getTokenSilently(o);
        this.user = await this.auth0Client.getUser();
        return token;
      },
```

Happy to submit a PR for this - but wanted to check that if that is wanted and/or the correct approach.
Thanks!

**Comment by stevehobbsdev** [comment]
@ndenny yep - happy to review a PR for this. Thanks!

**Comment by ndenny** [comment]
FYI - submitted #166 for this

**Comment by stevehobbsdev** [comment]
Thanks for your patience here, this will get merged this week.
