### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by marclave** [auth0-samples/auth0-vue-samples#16]
In the quickstart [documentation](https://manage.auth0.com/#/clients/1QvnoKp5mbL-OF1RNRtBKlHcwUhjAzd4/quickstart) there is a typo at this line, should be `authorization` not `authorizaton`
```

this.lock.on('authorizaton_error', (error) => {
    // handle error when authorization fails
  });

```

**Comment by elkdanger** [comment]
Thanks for the feedback @marclave - the docs have been re-written and should now be correct.
