### ISSUE TITLE
Flash profile page when accessed by URL

### ISSUE THREAD

**Issue by ClementVanPeuter** [auth0-samples/auth0-vue-samples#167]
Everything work like a charm.
But when trying to access the profile page by url when we are NOT logged in ( just type /profile after base url) the page/view flash for like 1/2 second before the loginWithRedirect is triggered.

The result is we see the profile page for a little, before the login redirection :/

I think it's our guard or our router code (but I can't figured out what ) and I found this annoying to see a protected page :/

**Comment by stevehobbsdev** [comment]
@ClementVanPeuter that doesn't sound ideal. The guard should wait for the `isAuthenticated` call to complete, but the fix for that will be somewhere in the wrapper. Let me take a look to see if I can replicate the issue in the sample 👍🏻

**Comment by stevehobbsdev** [comment]
It looks like you can prevent the target page from being loaded by using `next(false)` when not authenticated. It'll remain on the page you were when the URL was changed. I've modified the base sample to take this into account (#168).

Let me know if that helps.
