### ISSUE TITLE
Vue2.0 deprecated lifecycle hook

### ISSUE THREAD

**Issue by marclave** [auth0-samples/auth0-vue-samples#17]
Noticed inside of package.json, Vue2.0 is being used. However, the lifecycle hook from 1.X to 2.X has changed `Ready()` to `mounted()`

https://vuejs.org/v2/guide/instance.html

https://github.com/auth0-samples/auth0-vue-samples/blob/master/01-Login/package.json#L20

In app.js you are using `mounted()` but the documentation on quickstart guide is not updated

**Comment by elkdanger** [comment]
Hey @marclave, the sample app has been updated since this issue was raised, and contains the correct lifecycle hooks.

I'll close this issue for now; if you're still having trouble, please feel free to submit another issue.
