### ISSUE TITLE
Vue 3 Incompatible

### ISSUE THREAD

**Issue by heyharmon** [auth0-samples/auth0-vue-samples#170]
Very excited to see your team's take on implementing the JS SDK with Vue 3 Composition API.

**Comment by stevehobbsdev** [comment]
I'm excited for it too @heyharmon! It's something we have on the roadmap, I just don't have a timeline to share at the moment. Keep an eye out for our updated [quickstarts](https://auth0.com/docs/quickstart/spa/vuejs), [community forums](https://community.auth0.com/) and socials for when it drops 🎉

**Comment by heyharmon** [comment]
Thank you @stevehobbsdev, cheers!
