### ISSUE TITLE
M1 Support

### ISSUE THREAD

**Issue by subnetmarco** [auth0-samples/auth0-vue-samples#175]
Doesn't work with Apple M1 cpus, because of an outdated version of `node-sass`.

**Comment by stevehobbsdev** [comment]
Thanks @subnetmarco, I'll get this updated.

**Comment by stevehobbsdev** [comment]
We will instead fix this in the upcoming `beta` branch for Vue 3 - upgrading `node-sass` requires Python, so instead we're potentially looking at removing that dependency.

Thanks for raising.
