### ISSUE TITLE
clicking on login does nothing?

### ISSUE THREAD

**Issue by v3nt** [auth0-samples/auth0-vue-samples#185]
Running the project, now errors on startup.

When I click on Login the only thing that happens is a redirect to the app with parameters -

http://localhost:3000/?error=invalid_request&error_description=no%20connections%20enabled%20for%20the%20client&state=MUc3ckN6SkgwUDZqZElTYWpLTXUuT3RzNVBDdGhGTzZwT2RGRWFuOFBoSA%3D%3D

No errors in console.
I have put my app details in `auth_config.json`

**Comment by stevehobbsdev** [comment]
👋🏻  The error "no connections enabled" would indicate that your app within the Auth0 Dashboard doesn't have any connections assigned to it (database, social, etc), so it's throwing an error.

Of course, we can be better at surfacing this in the sample app. @frederikprijck can we look at this for the new beta samples?

**Comment by v3nt** [comment]
thanks -  thought as much but I'm following the examples from the application I've created and can't see how to create connections?

**Comment by v3nt** [comment]
actually I can see I add them via the connections tab. Apologies - I thought this was going to be from the sample project somewhere.

**Comment by frederikprijck** [comment]
@stevehobbsdev  The new beta QuickStart sample does show a message in this case:

![image](https://user-images.githubusercontent.com/2146903/154486318-9c17fe28-5f1b-4240-8e85-9cd12a7fca25.png)

The current Sample does indeed not show any message as it's not configured to parse the error query params on redirect.

**Comment by stevehobbsdev** [comment]
Awesome, thanks for clarifyjng.

@v3nt glad you got it sorted. Like @frederikprijck has shown the experience is better with the new samples. Thanks for raising the issue
