### ISSUE TITLE
Uncaught TypeError: Cannot destructure property 'getAccessTokenSilently' of 'useAuth0(...)' as it is undefined.

### ISSUE THREAD

**Issue by onurusluca** [auth0-samples/auth0-vue-samples#201]
Hi!

This is for a discussing but there is no discussion section so I am posting here.
This may not be a problem about auth0-vue I don't know. Correct me if I am wrong.

I am trying to use getAccessTokenSilently on Vue 3 Composition API with script setup.

Use:
```
import { useAuth0 } from "@auth0/auth0-vue";

const { getAccessTokenSilently} = useAuth0() // PROBLEM

async function getTokenSilently() {
   const accessTokenData = await getAccessTokenSilently(options); 

  return {
    access_token: accessTokenData,
  };
}

// And then use the getTokenSilently somewhere else in a .vue file.
```

This will give: 

> Uncaught TypeError: Cannot destructure property 'getAccessTokenSilently' of 'useAuth0(...)' as it is undefined.

This also happens in a .vue file.
isLoading etc. will give the same error.

Can you please tell me what I am doing wrong?

**Comment by frederikprijck** [comment]
It's hard to tell without a reproduction. Please provide a reproduction for us to look into. Also be sure to follow https://auth0.com/docs/quickstart/spa/vuejs/01-login

**Comment by onurusluca** [comment]
@frederikprijck Thanks for the quick answer.

Here is the reproduction: https://vitejs-vite-ghgzmw--3000.local.webcontainer.io
Remove `const { getAccessTokenSilently } = useAuth0();`  to see the h1 tag. With that code it won't show.
For some reason it doesn't show the error though. Probably cause of the compiler.

**Comment by onurusluca** [comment]
@frederikprijck This also seems to happen with route guard:
![image](https://user-images.githubusercontent.com/51825926/161712350-d4f0d0ee-f13a-49cf-8145-614a0102e2bf.png)

```
import { authGuard } from "@auth0/auth0-vue";
const routes: Array<RouteRecordRaw> = [
  {
    path: "/:contractId?",
    name: "Home",
    component: Home,
    beforeEnter: authGuard,
  }
  ];
  
  const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes, // short for `routes: routes`
});

export default router;

```

**Comment by frederikprijck** [comment]
I have no access to that URL, however that URL wont help much. Can you send me a github repository that containes the issue ?

**Comment by onurusluca** [comment]
My bad: https://stackblitz.com/edit/vitejs-vite-ghgzmw?file=src%2FApp.vue&terminal=dev
I can't currently create a github with the problem. If the reproduction link isn't enough, you can close the Issue.

**Comment by frederikprijck** [comment]
There appear to be some issues with how the stackblitz is set up.  I made some changes, mostly changing

```
const Auth0Service = () => {
  createAuth0({
    client_id: 'client_id',
    domain: 'domain',
    redirect_uri: window.location.origin,
  });
};

```
to
```
createApp(App)
  .use(
    createAuth0({
      client_id: 'client_id',
      domain: 'domain',
      redirect_uri: window.location.origin,
    })
  )
  .mount('#app');
```
That and uncommenting `//const { getAccessTokenSilently } = useAuth0();` in App.vue removes the error, but things still do not work because of how you are setting things up. Please refer to https://auth0.com/docs/quickstart/spa/vuejs/01-login on how to use the SDK in Vue, it should be pretty identical when using the script setup approach.
