### ISSUE TITLE
Login samples Production mode issue

### ISSUE THREAD

**Issue by armujahid** [auth0-samples/auth0-vue-samples#23]
Login sample are not working in production mode.
**Steps to reproduce issue 1**
1. `npm install --only=production`
2. `npm start` 

**Error 1**
module.js:471
    throw err;
    ^
Error: Cannot find module 'chalk'
**Conclusion 1**
Not all devDependencies are devDependencies. Some devDependencies should be moved to dependencies section

**Issue 2**
Even after installation of all dependencies using `npm install` in development mode, App won't run in production mode although it works fine in development mode.

**Production mode error after installation of all dependencies**

> auth0-vue-samples@1.0.0 start L:\01-login
> node build/dev-server.js

npm WARN invalid config loglevel="notice"

 ERROR  Failed to compile with 3 errors                              12:00:51 AM

 error  in ./src/App.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (L:\01-login\node_modules\extract-text-webpack-plugin\loader.js:25:9)

 @ ./src/App.vue 2:2-371
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Home.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (L:\01-login\node_modules\extract-text-webpack-plugin\loader.js:25:9)

 @ ./src/components/Home.vue 2:2-381
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Callback.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (L:\01-login\node_modules\extract-text-webpack-plugin\loader.js:25:9)

 @ ./src/components/Callback.vue 2:2-385
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080

**Comment by elkdanger** [comment]
Hey @armujahid, the sample app has been updated since this issue was raised. The new sample should work fine in this scenario, and provides Docker builds for the apps too if that's an option for you.

I'll close this issue for now; if you're still having trouble, please feel free to submit another issue.
