### ISSUE TITLE
White screen of death on Safari (Windows, iOS) and Chrome (iOS)

### ISSUE THREAD

**Issue by armujahid** [auth0-samples/auth0-vue-samples#24]
Login sample not working on Safari (Windows, iOS) and Chrome iOS. White screen is shown whenever site is opened. Samples are working perfectly on windows (Chrome, Firefox).

I can see the following error in console on Safari (Windows, iOS)
`Syntaxerror: unexpected keyword 'const'. const declarations are not supported in strict mode.
`
Issue not resolved even after replacing all occurrences of `const` (except in node_modules) with `var`,
So I think some modifications are required in webpack configs or installed modules to generate ES5 compatible code without const keyword.

**Comment by elkdanger** [comment]
Hey @armujahid, the sample app has been updated since this issue was raised, and does appear to work OK in Safari.

I'll close this issue for now; if you're still having trouble, please feel free to submit another issue.
