### ISSUE TITLE
Wrong apiUrl parameter in Vue sample project.

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-vue-samples#32]
When download the Sample project, the parameter apiUrl in\01-login\src\auth\auth0-variables.js is not propely prepopulated.

I'm logged in a tenant in Australia region, and the apiUrl parameter still shows the audience from the European region tenant.

AUTH-3349

**Comment by elkdanger** [comment]
@paulioceano, the sample app has been updated since this issue was raised. We made sure that the new samples do properly pre-populate variables.

I'll close this issue for now. If you're still having trouble, please feel free to submit another issue.
