### ISSUE TITLE
error in npm run buil

### ISSUE THREAD

**Issue by ildella** [auth0-samples/auth0-vue-samples#35]
Fresh checkout, run npm install then npm run build. It works but at the end I get this error. 
using nove 8.9.0 on ubuntu 17.04. 
```
ERROR in static/js/vendor.f04c1d01f4534f33e779.js from UglifyJs
Unexpected token: name (EventEmitter) [./node_modules/EventEmitter/src/index.js:16,0][static/js/vendor.f04c1d01f4534f33e779.js:21113,6]
```

**Comment by elkdanger** [comment]
Hey @ildella, the sample app has been updated since this issue was raised. I'll close this issue for now, if you're still having trouble, please feel free to submit another issue.
