### ISSUE TITLE
Is isAuthenticated() Reliable?

### ISSUE THREAD

**Issue by crouchcd** [auth0-samples/auth0-vue-samples#50]
I am able to update localStorage with `localStorage.setItem('expires_at', Date.now() + 86400000)` which sets the expiration to 24 hours later. After setting that, I refresh the application and I am "logged in." 

Perhaps checking the expiration alone is not a sufficient method of determining if a user is authenticated. Or it could just be a misunderstanding on my part.

**Comment by srini85** [comment]
@crouchcd - usage of auth in client side is handy to only obfuscate authentication. You can always alter the js to allow u to proceed. It's useful for just first line of defence, but any data you get back, the token has to be verified server side. Here, altering your storageitem will not help

**Comment by elkdanger** [comment]
Hey @crouchcd, the sample app has been updated since this issue was raised and more checks are in place to determine the login state. I'll close this issue for now, if you're still having trouble, please feel free to submit another issue.
