### ISSUE TITLE
Error during npm start

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-vue-samples#52]
Got an error when running npm start, can not find module "Chalk."

![screenshot_2](https://user-images.githubusercontent.com/15818783/44244251-fe6a0380-a1a0-11e8-916c-a083ec7a0689.png)

**Comment by albertoperdomo** [comment]
Can't reproduce. Can you please try to reproduce again calling `npm install', then `npm start` @paulioceano ?

**Comment by elkdanger** [comment]
Hey @paulioceano, the sample app has been updated since this issue was raised. I'll close this issue for now, if you're still having trouble, please feel free to submit another issue.
