### ISSUE TITLE
Feedback on the Vue samples

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-vue-samples#56]
I am an old friend of Auth0, even worked for a while on improving Aurelia samples set (more on that at a different time) and am currently interested in Auth0 support for Vue. Unlike my previous work on a few Aurelia Open Source projects, I am now looking at Auth0 as the identity management provider for a big company in the healthcare market that hired me as the "adviser to the CEO".

With this explanation, allow me a few critical comments on the incomplete **[Vue QuickStart samples](https://github.com/auth0-samples/auth0-vue-samples)**:

### 1. Missing samples
This existing set has only **[01-Login](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login)** and **[05-Authorization](https://github.com/auth0-samples/auth0-vue-samples/tree/master/05-Authorization)** samples. I believe that for the consistency reasons, the samples set should follow the structure and content of the **[auth0-javascript-samples](https://github.com/auth0-samples/auth0-javascript-samples)** set.

### 2. Sample 01-Login is a lot more complicated than it should be
Just check the **[list of dev-dependencies](https://github.com/auth0-samples/auth0-vue-samples/blob/master/01-Login/package.json#L27-L88)** - and my characterization would seem mild 😄

### 3. `npm install` command results with indication of serious problems
```
λ npm install
npm WARN extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 116 packages from 394 contributors and audited 10559 packages in 9.437s
found 21 vulnerabilities (11 low, 1 moderate, 7 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```
### 4. Samples are not created with Vue CLI 3.x
I am of the firm opinion that each of the samples targeting the specific platform, should follow the "coding practices" of these platforms.

**Comment by albertoperdomo** [comment]
Hello @adriatic,

thanks for reaching out and taking the time to submit this feedback.
We are currently in the process of reviewing all our Quickstarts. We are aware that the Vue Quickstart needs some love.

I am taking note and will see that will make these improvements, as they all seem to make sense. Some of that might happen in the short term, some in the mid term.

**Comment by adriatic** [comment]
Hello @albertoperdomo - thanks for responding. Allow me to suggest the article **[How to add Auth0 Authentication to a Vue.js Application in 7 steps](https://www.storyblok.com/tp/how-to-auth0-vuejs-authentication), written by a friend (Dominik Angerer, Storyblok's CEO) who was so disappointed by Auth0 Vue quickstart to actually write a better version himself.

My point is this: the samples for any supported platform ought to be written using the "platform specific style" (like packaging Auth0 specific code in the form of a Vue plugin), instead of making all samples be copies of the **[generic JavaScript](https://github.com/auth0-samples/auth0-javascript-samples)** sample.

**Comment by albertoperdomo** [comment]
What you are saying certainly makes sense and resonates with me.
Thanks for pointing to that article. It certainly helps.

**Comment by adriatic** [comment]
I do like your response a lot 👍 Alberto. I am aware that you recently joined Auth0 with the task to give the samples and related documentation the needed love. Welcome! 

I am a close friend of Auth0 for many years and am really looking forward to see the result of your contributions.
