### ISSUE TITLE
Error during npm install

### ISSUE THREAD

**Issue by djrasmusp** [auth0-samples/auth0-vue-samples#59]
I get an error, when running "npm install"

```
npm ERR! Unexpected string in JSON at position 3485 while parsing '{
npm ERR!   "name": "auth0-vue-samples",
npm ERR!   "vers'
```

And i can figure out where the problem lies, since this is directly download from the master.

**Comment by albertoperdomo** [comment]
Is this when downloading from https://auth0.com/docs/quickstart/spa/vuejs or when cloning the repo?
If it's when cloning the repo, which directory are you running the npm command in?

**Comment by djrasmusp** [comment]
Get same error on both

**Comment by albertoperdomo** [comment]
Sorry, just reverted a bad merge.
Should be working now if you update from master.

**Comment by albertoperdomo** [comment]
Thanks for reporting @djrasmusp !
