### ISSUE TITLE
Missing profile data

### ISSUE THREAD

**Issue by davestewart** [auth0-samples/auth0-vue-samples#69]
When we run the demo locally, we can authenticate etc, but `$auth.profile` does not contain profile data as outlined [here](https://auth0.com/docs/users/references/user-profile-structure) but rather the claims data:

```
{
  "iss": "...",
  "sub": "...",
  "aud": "...",
  "iat": ...,
  "exp": ...,
  "nonce": "..."
}
```

The docs here seem to confirm this:

- https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims

Is there a reason the code in this demo seems to be different (i.e. having profile data returned in the auth call) to what the docs describe (claims only) ?

Perhaps the repo is out of date?

**Comment by elkdanger** [comment]
@davestewart Apologies for the delay in replying. This could be down to the Auth0 app you're authenticating with. When you log in, are you using a social provider such as Google or Facebook, or are you using a username and password?

**Comment by davestewart** [comment]
Hey Steve, no worries!

We're using username and password.

One of the guys from Auth 0 was helping us out in the forum then on private message but he's gone on leave this week and we haven't followed it up yet.

It's very strange - we set this project up only in the last couple of weeks so assumed the "latest and greatest" would just work, but we get claims when everyone else gets profile data.

Hopefully you can help!

**Comment by elkdanger** [comment]
I can certainly try - have you got a repo I can have a look at?

**Comment by davestewart** [comment]
TBH, it's just the one from here.

This what I see with a vanilla project and updated `auth_config.json`:

![image](https://user-images.githubusercontent.com/132681/56283030-7dd11d80-6108-11e9-9820-3051de8ef9e3.png)

**Comment by elkdanger** [comment]
I'm assuming if it's vanilla that you haven't modified the scopes from the default `openid email profile`:

https://github.com/auth0-samples/auth0-vue-samples/blob/master/01-Login/src/auth/authService.js#L10

Do you get the same thing if you log in with a social provider e.g., Google?

**Comment by davestewart** [comment]
> Do you get the same thing if you log in with a social provider

Not sure. Do I need to set that up in code first?

**Comment by elkdanger** [comment]
@davestewart The social connections are set up through the Auth0 dashboard, then you can toggle them per-app. Once that's done, the social providers you choose will be presented as an option for your users when they log in. You shouldn't have to configure anything different in code for that to work.

I'll [link you to this](https://auth0.com/docs/identityproviders) but unhelpfully doesn't show you how to _add_ a social connection, but if you head to the [right place in your dashboard](https://manage.auth0.com/#/connections/social), _hopefully_ it's intuitive enough. Give us a shout if you're having trouble finding something.

**Comment by elkdanger** [comment]
@davestewart Hopefully you've solved your issue. If not, feel free to re-open or raise another issue.
