### ISSUE TITLE
Global mixin

### ISSUE THREAD

**Issue by davestewart** [auth0-samples/auth0-vue-samples#70]
Hi there,

Just checking out this project for a new Vue project.

I've been trying to understand the global mixin approach, but having given it a good going over, I'm not sure it's the best way to do things in Vue, though I see what it is trying to demonstrate.

Being a global mixin, it adds the `created` and `destroyed` lifecycle hooks to every component instance in your app; there could be 100s or 1000s of these (every item in a list, for example).

The purpose appears to be to check if the component has a `handleLogin` method. This could be done by making the mixin local, and just including it in the components that need it:

```js
export default {
  mixins: [Auth],
}
```

Secondly, adding an event listener, doesn't work on a component unless it is on the screen as you log in. For example, the code which assigns the profile data to the profile component will store it only whilst that component is on the screen. As soon as you navigate and come back, the data is lost.

https://github.com/auth0-samples/auth0-vue-samples/blob/master/01-Login/src/views/Profile.vue#L27-L29

There are several ways you could do this in Vue:

- javascript module
- local storage
- shared store
- vuex

I'm just not sure Vue benefits from having event listeners spread across components when its own reactivity engine would handle this natively.

I can submit a PR if you like?

**Comment by elkdanger** [comment]
@davestewart I agree, a move to manually including the mixin where it's needed would be more beneficial, especially as the app scales. We're about to go through a round of feedback on the app and I'd like to include changes such as this. Thanks!

Regarding the event listeners, an alternative approach as you suggest would be good to see, and feel free to submit a PR! I'd like to avoid using local storage and Vuex, but if you can suggest something else then I'd love to see it.

**Comment by davestewart** [comment]
Hey Steve,

Actually in my travels I found the following article, and it's very similar to the way I'm doing things at the moment, but more thought through as right now I'm just wrapping the supplied library from the demo:

- https://www.storyblok.com/tp/how-to-auth0-vuejs-authentication

The trick is to use a `new Vue()` as a model only... this makes it reactive from the outset and is also nice to package up the methods.

This can then be used as a plugin, mixin, or even standalone.

> Regarding the event listeners, an alternative approach as you suggest would be good to see

Yeah, the Vue approach would be to have a single reactive element which any other element can just include in its `data`or `computed` blocks... or reference directly as mentioned.

> I'd like to avoid using local storage and Vuex

Vuex, I totally understand and I agree it's an extra layer to be forced on people.

Local storage - how come? To me it makes more sense as you don't need the extra call to Auth0 when the site loads, and `getAccessToken()` handles this when making the call to the API.

The other thing I found with the demo, is there's a LOT of extra stuff that just doesn't need to be there; dependencies, assets, icons, code formatting, directives, dropdown menus, mobile and desktop navigation, marketing text, etc etc.

I found this to be extremely cumbersome when trying to get to the nub of things with the auth.

As an example of a demo I would find much easier to pull apart, one of mine:

- https://vee-element.netlify.com
- https://github.com/davestewart/vee-element/tree/master/demo

Just much less to load, grok and compile.

At the very least if I PR, could I remove all the extra things like fonts, plugins, directives, etc?

The point is to learn Auth0, not Vue after all.

**Comment by elkdanger** [comment]
> Local Storage: Is there a reason in particular why you're not keen?

Local Storage is getting a lot of heat right now in this space as people had a history of storing sensitive data there (like access tokens). I mentioned this on the other issue but [this is worth reading](https://auth0.com/docs/security/store-tokens#don-t-store-tokens-in-local-storage) on our stance on local storage generally.

Even if it's for non-sensitive data, it's still susceptible to XSS and it's not in our interest to promote storing anything there if it can be avoided.

> At the very least if I PR, could I remove all the extra things like fonts, plugins, directives, etc?

Hold off on that for now. The styling of these apps (what we call "Quickstarts", ironically) is somewhat of a coordinated effort across all our quickstart apps.

**However**, I _am_ extremely interested in the feedback you've given as one of the things I would like to ascertain is whether this approach of writing docs for the basic auth case, then supplying a more fully-featured app as an example, is working for us.

Did you check out the [associated docs](https://auth0.com/docs/quickstart/spa/vuejs), and with that in combination with this sample app, do you still feel that it's too much for readers?

**Comment by davestewart** [comment]
Thanks for the info!

Those quick starts looks great. Though it's the first time I've seen them.

Not sure if I should have looked harder?

**Comment by elkdanger** [comment]
> Not sure if I should have looked harder?

No not necessarily. I would have imagined that the route in to these repositories would normally be through the quickstart docs, as the reader is prompted to visit here to grab the sample app.

I was just wondering if following through the docs would be clearer, but I know a good percentage of people like to dive into the code straight away (myself included). It's a balance we're trying hard to strike, between providing simple instructions vs. a compelling sample application.

**Comment by elkdanger** [comment]
@davestewart The topics discussed in the opening post are being addressed in a rewrite of the sample with [the new Auth0 JS SDK](https://github.com/auth0/auth0-spa-js). Closing this for now, but if there is still something to discuss, feel free to re-open or raise another issue.
