### ISSUE TITLE
After 'Log In' the home page still shows not logged in

### ISSUE THREAD

**Issue by dyardyGIT** [auth0-samples/auth0-vue-samples#84]
The issue that i first noticed, whats the home page shows' at first Log In, after I log in i get redirected to universal log in and then back to home  (root) however it still says Log In (at this moment isAuthenticated page variable is null).  Well it does get set to true but then due to data.state.target is undefined it gets set to false again)

After I click log in, it makes the call to Auth0, gets authenticated and returns to callback component, which redirects to the root and at this moment  and the navbar component reads the loggedIn value (which is true at this moment)

(within navbar.vue)
handleLoginEvent(data) {
      this.isAuthenticated = data.loggedIn; ///Right here it is true
      this.profile = data.profile;
 }

however, it also hits the method handleLoginEvent within the callback.vue at which point !data.error returns true and then does $route.push(data.state.target || "/") which in which data.state is null and so throws exception setting data.loggedIn to false (and the navbar then shows the user as not logged in but in fact he/she is)

methods: {
    handleLoginEvent(data) {
      if (!data.error) {
        **this.$router.push(data.state.target || "/");**
      }
    }
  }

why am i getting data.state =null (which causes exception when trying to access data.state.target as it is now undefined)?

**Comment by dyardyGIT** [comment]
I believe the download code/sample that embeds your application config is not aligned with this github sample.
I believe this resolved the issue within authService.js

    this.emit(loginEvent, {
      loggedIn: true,
      profile: authResult.idTokenPayload,
      state: authResult.appState **|| {}**
    });

Is the github repository more current?

**Comment by tim-yao** [comment]
I tried the Login example with Auth0 default app, I failed to login as well. Fixed the issue by update the default app setting based on this: https://auth0.com/docs/errors/libraries/auth0-js/invalid-token#parsing-an-hs256-signed-id-token-without-an-access-token

**Comment by stevehobbsdev** [comment]
Please let me know if you have not managed to solve this issue yet - happy to continue the discussion.
