### ISSUE TITLE
Logout not displayed properly

### ISSUE THREAD

**Issue by mpaktiti** [auth0-samples/auth0-vue-samples#9]
I download and run the sample but after I successfully login I still see the `Login` button instead of the `Logout`. If I press `Login` again and once Lock loads close it (without logging in again) I can see the `Logout` button.

![vuejs](https://cloud.githubusercontent.com/assets/11715799/18242225/f1302b0e-735d-11e6-8326-48644aa58133.gif)

**Comment by matthewlilley** [comment]
Same here

**Comment by Amialc** [comment]
AUTH-3500

**Comment by chenkie** [comment]
Fixed in latest :)
