### ISSUE TITLE
After login, refreshing the page and returning information is too slow.

### ISSUE THREAD

**Issue by shikkk** [auth0-samples/auth0-vue-samples#95]
After logging in, refreshing the page, some methods and user information returned by auth0 are particularly slow, and it takes about a minute to wait. Have you encountered such a problem again?

**Comment by stevehobbsdev** [comment]
@shikkk Thanks for raising this. Can you read [this FAQ item](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-does-the-auth0client-object-take-a-long-time-to-initialize) and see if that helps you?
